//! Serializes a MistakeCard back into the canonical mistake `.md` format (the
//! exact shape the Android app writes — see SYNC-PROTOCOL.md). Used to push
//! desktop LLM enrichments back to the repo.

use crate::models::MistakeCard;

const PLACEHOLDER: &str = "_Not yet analyzed — will be filled on first desktop sync._";

pub fn build_mistake_markdown(card: &MistakeCard) -> String {
    let tags = if card.tags.is_empty() {
        "[]".to_string()
    } else {
        format!("[{}]", card.tags.join(", "))
    };
    let options = card
        .options
        .iter()
        .map(|o| format!("- {o}"))
        .collect::<Vec<_>>()
        .join("\n");

    let rows = card
        .attempts
        .iter()
        .enumerate()
        .map(|(i, a)| {
            format!(
                "| {} | {} | {} | {} | {} | {} |",
                i + 1,
                a.date,
                a.answer,
                if a.correct { "✅" } else { "❌" },
                if a.time_taken.is_empty() { "-" } else { &a.time_taken },
                if a.context.is_empty() { "-" } else { &a.context }
            )
        })
        .collect::<Vec<_>>()
        .join("\n");

    let key_fact = if card.key_fact.is_empty() { PLACEHOLDER } else { &card.key_fact };
    let why_wrong = if card.why_wrong.is_empty() { PLACEHOLDER } else { &card.why_wrong };

    format!(
        "---\n\
        id: {id}\n\
        subject: {subject}\n\
        topic: {topic}\n\
        source_file: {source_file}\n\
        tags: {tags}\n\
        error_type: {error_type}\n\
        first_wrong: {first_wrong}\n\
        last_wrong: {last_wrong}\n\
        times_wrong: {times_wrong}\n\
        times_correct: {times_correct}\n\
        is_resolved: {is_resolved}\n\
        ---\n\n\
        # {id}\n\n\
        ## Question\n\n{question}\n\n\
        ## Options\n\n{options}\n\n\
        ## Your Answer\n\n{user_answer}\n\n\
        ## Correct Answer\n\n{correct_answer}\n\n\
        ## Key Fact (generated by LLM)\n\n{key_fact}\n\n\
        ## Why You Got It Wrong (generated by LLM)\n\n{why_wrong}\n\n\
        ## Attempts\n\n\
        | # | Date | Answer | Result | Time | Context |\n\
        |---|---|---|---|---|---|\n\
        {rows}\n",
        id = card.id,
        subject = card.subject,
        topic = card.topic,
        source_file = card.source_file,
        tags = tags,
        error_type = card.error_type,
        first_wrong = card.first_wrong,
        last_wrong = card.last_wrong,
        times_wrong = card.times_wrong,
        times_correct = card.times_correct,
        is_resolved = card.is_resolved,
        question = card.question,
        options = options,
        user_answer = card.user_answer,
        correct_answer = card.correct_answer,
        key_fact = key_fact,
        why_wrong = why_wrong,
        rows = rows
    )
}
