import type { MistakeCard } from '../shared/types'

/**
 * Serializes a MistakeCard back into the canonical mistake `.md` format — the
 * exact shape the Android app writes (see SYNC-PROTOCOL.md). Used to push
 * desktop LLM enrichments (key fact / why wrong / tags / error type) back to
 * the repo so they survive cache clears and reach every device.
 */
export function buildMistakeMarkdown(card: MistakeCard): string {
  const tags = card.tags.length ? `[${card.tags.join(', ')}]` : '[]'
  const options = card.options.map((o) => `- ${o}`).join('\n')

  const attemptRows = card.attempts
    .map(
      (a, i) =>
        `| ${i + 1} | ${a.date} | ${a.answer} | ${a.correct ? '✅' : '❌'} | ${a.timeTaken || '-'} | ${a.context || '-'} |`
    )
    .join('\n')

  const attempts = attemptRows
    ? `| # | Date | Answer | Result | Time | Context |\n|---|---|---|---|---|---|\n${attemptRows}`
    : '| # | Date | Answer | Result | Time | Context |\n|---|---|---|---|---|---|'

  return `---
id: ${card.id}
subject: ${card.subject}
topic: ${card.topic}
source_file: ${card.sourceFile}
tags: ${tags}
error_type: ${card.errorType}
first_wrong: ${card.firstWrong}
last_wrong: ${card.lastWrong}
times_wrong: ${card.timesWrong}
times_correct: ${card.timesCorrect}
is_resolved: ${card.isResolved}
---

# ${card.id}

## Question

${card.question}

## Options

${options}

## Your Answer

${card.userAnswer}

## Correct Answer

${card.correctAnswer}

## Key Fact (generated by LLM)

${card.keyFact || '_Not yet analyzed — will be filled on first desktop sync._'}

## Why You Got It Wrong (generated by LLM)

${card.whyWrong || '_Not yet analyzed — will be filled on first desktop sync._'}

## Attempts

${attempts}
`
}
